### ISSUE TITLE
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [864,0,0] Assertion `t >= 0 && t < n_classes` failed.

### ISSUE THREAD

**Issue by jieruyao49** [lxasqjc/Deformation-Segmentation#20]
when I running the train_deform.py on the Cityscape dataset, I encountered the following error. I have checked that the numerical range of batch_data['seg_label'] is between 0 and 19. However, the code allows a range between 0 and 18. How should I solve this problem?

```
[2023-03-24 12:00:53,725 INFO train_deform.py line 693 48563] Outputing checkpoints to: ckpt/Cityscape_Tin_64_128_ours
/data/anaconda3/envs/deform_seg_env/lib/python3.8/site-packages/torch/nn/functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn( # samples: 2975 1 Epoch = 744 iters
/data/PycharmProjects/high_resolution/Deformation-Segmentation-main/models/models.py:416: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  xs = nn.Softmax()(xs) # N,W*H
/data/anaconda3/envs/deform_seg_env/lib/python3.8/site-packages/torch/nn/functional.py:3981: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/data/anaconda3/envs/deform_seg_env/lib/python3.8/site-packages/torch/cuda/memory.py:260: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
THCudaCheck FAIL file=../aten/src/THC/THCCachingHostAllocator.cpp line=278 error=710 : device-side assert triggered
Traceback (most recent call last):
  File "/data/PycharmProjects/high_resolution/Deformation-Segmentation-main/train_deform.py", line 731, in <module>
    main(cfg, gpus)
  File "/data/PycharmProjects/high_resolution/Deformation-Segmentation-main/train_deform.py", line 522, in main
    train(segmentation_module, iterator_train,
  File "/data/PycharmProjects/high_resolution/Deformation-Segmentation-main/train_deform.py", line 73, in train
    loss, acc, edge_loss = segmentation_module(batch_data[0], writer=writer, count=cur_iter, epoch=epoch)
  File "/data/anaconda3/envs/deform_seg_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/PycharmProjects/high_resolution/Deformation-Segmentation-main/models/models.py", line 607, in forward
    acc = self.pixel_acc(pred, feed_dict['seg_label'])
  File "/data/PycharmProjects/high_resolution/Deformation-Segmentation-main/models/models.py", line 194, in pixel_acc
    acc_sum = torch.sum(valid * (preds == label).long())
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [864,0,0] Assertion `t >= 0 && t < n_classes` failed.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/data/anaconda3/envs/deform_seg_env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/anaconda3/envs/deform_seg_env/lib/python3.8/threading.py", line 870, in run

```

**Comment by jieruyao49** [comment]
I have already solved this problem. Based on the information provided in [cityscapes](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py)，value 19 indicates license plate class, so we just need to set the value of 19 in annotation to 0.
